name: cmp
channels:
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.115
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cudatoolkit=11.3.1
  - freetype=2.10.4
  - giflib=5.2.1
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.12
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - ncurses=6.3
  - openjpeg=2.4.0
  - openssl=3.0.5
  - pip=22.1.2
  - pthread-stubs=0.4
  - python=3.10.5
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - six=1.16.0
  - sqlite=3.39.0
  - tbb=2021.5.0
  - tk=8.6.12
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.1.0
    - accelerate==0.10.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==1.3.0
    - ale-py==0.8.0
    - altair==4.2.0
    - antlr4-python3-runtime==4.9.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - autopep8==1.6.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - avro==1.11.1
    - babel==2.11.0
    - backcall==0.2.0
    - base58==2.1.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.4
    - bokeh==2.4.3
    - cachetools==5.2.0
    - certifi==2022.6.15
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - clldutils==3.16.0
    - cloudpickle==2.1.0
    - colorama==0.4.6
    - colorcet==3.0.0
    - colorlog==6.7.0
    - colorlover==0.3.0
    - commonmark==0.9.1
    - csvw==3.1.3
    - cufflinks==0.17.3
    - cycler==0.11.0
    - dask==2022.8.0
    - datasets==2.4.0
    - datashader==0.14.2
    - datashape==0.5.2
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - distributed==2022.8.0
    - docker-pycreds==0.4.0
    - emoji==2.0.0
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - evaluate==0.2.2
    - executing==0.9.1
    - fastavro==1.5.1
    - fastjsonschema==2.15.3
    - filelock==3.7.1
    - flatbuffers==1.12
    - fonttools==4.34.4
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - fst-pso==1.8.1
    - fuzzytm==2.0.5
    - gast==0.4.0
    - gensim==4.3.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - h5py==3.7.0
    - heapdict==1.0.1
    - holoviews==1.15.0
    - huggingface-hub==0.8.1
    - hydra-core==1.2.0
    - idna==3.3
    - imageio==2.21.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.10.0
    - iniconfig==1.1.1
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - isodate==0.6.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.7.2
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - language-tags==1.1.0
    - libclang==14.0.1
    - llvmlite==0.39.0
    - locket==1.0.0
    - lxml==4.9.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - miniful==0.0.6
    - mistune==0.8.4
    - mmcls==0.25.0
    - mmcv==1.7.1
    - mmsegmentation==0.29.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - multipledispatch==0.6.0
    - multiprocess==0.70.13
    - mypy==0.901
    - mypy-extensions==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.5
    - nltk==3.7
    - notebook==6.4.12
    - numba==0.56.0
    - numpy==1.22.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.0
    - omegaconf==2.2.3
    - openai==0.22.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.7.0.68
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.3
    - pandas-stubs==1.4.3.220807
    - pandavro==1.7.1
    - pandocfilters==1.5.0
    - panel==0.13.1
    - param==1.12.2
    - parso==0.8.3
    - partd==1.2.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - plotly==5.10.0
    - pluggy==0.13.1
    - prettytable==3.5.0
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.30
    - protobuf==3.20.1
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pyct==0.4.8
    - pydeck==0.7.1
    - pyfume==0.2.25
    - pygments==2.12.0
    - pylatexenc==2.10
    - pympler==1.0.1
    - pynndescent==0.5.7
    - pyparsing==3.0.9
    - pyprg==0.1.1b7
    - pyrsistent==0.18.1
    - pytest==6.2.4
    - pytest-mypy==0.8.1
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyviz-comms==2.2.0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qudida==0.0.4
    - rdflib==6.2.0
    - regex==2022.7.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - rich==12.5.1
    - rsa==4.8
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scikit-learn-extra==0.2.0
    - scipy==1.9.0
    - seaborn==0.11.2
    - segment==0.2.0
    - segments==2.2.1
    - semver==2.13.0
    - send2trash==1.8.0
    - sentry-sdk==1.9.3
    - setproctitle==1.3.1
    - setuptools==63.1.0
    - shortuuid==1.0.9
    - simpful==2.9.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - streamlit==1.11.1
    - streamlit-chat==0.0.2.1
    - streamlit-plotly-events==0.0.6
    - tabulate==0.9.0
    - tblib==1.7.0
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.8
    - timm==0.6.12
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.13.1
    - torchaudio==0.12.1
    - torchmetrics==0.10.0
    - torchvision==0.14.1
    - torchviz==0.0.2
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.3.0
    - transformers==4.21.1
    - types-pytz==2022.1.2
    - tzdata==2022.1
    - tzlocal==4.2
    - umap-learn==0.5.3
    - uritemplate==4.1.1
    - urllib3==1.26.11
    - validators==0.20.0
    - wandb==0.13.7
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.1.2
    - widgetsnbextension==3.6.1
    - wrapt==1.14.1
    - xarray==2022.6.0
    - xxhash==3.0.0
    - yapf==0.32.0
    - yarl==1.7.2
    - zict==2.2.0
    - zipp==3.8.1
